articles/urls.py
from django.urls import path
from articles import views


app_name = "articles"

urlpatterns = [
    path("", views.article_list, name="list"),
    path("<slug:slug>/", views.article_detail, name="detail"),
]

website/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from website import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("refsheet/", views.refsheet, name="refsheet"),
    path("articles/", include("articles.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from articles.models import Article


def article_list(request):
    articles = (
        Article.objects.defer("body").filter(published=True).order_by("-date").all()
    )
    return render(request, "views/articles.html", {"articles": articles})


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)

    if not article.published:
        return HttpResponse("Not found")

    return render(request, "views/article.html", {"article": article})

website/views.py
from django.shortcuts import render


def index(request):
    return render(request, "views/index.html")


def refsheet(request):
    return render(request, "views/refsheet.html")

templates/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Leggy Land{% endblock %}</title>

        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <meta name="description" content="{% block description %}Fluffy's mid-ass page{% endblock %}"/>
        <link rel="shortcut icon" type="image/png" href="{% static 'icon.jpg' %}"/>

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=IBM+Plex+Mono&display=swap" rel="stylesheet"/>

        <script defer data-domain="gay.leggy.dev" src="https://plausible.leggy.dev/js/script.js"></script>

        {% compress css %}
            <link type="text/x-sass" href="{% static 'sass/styles.sass' %}" rel="stylesheet" media="screen"/>
            <link type="text/css" href="{% static 'css/array.css' %}" rel="stylesheet" media="screen"/>
            <link type="text/css" href="{% static 'css/khand.css' %}" rel="stylesheet" media="screen"/>
            <link type="text/css" href="{% static 'css/zodiak.css' %}" rel="stylesheet" media="screen"/>
        {% endcompress %}
    </head>

    <body>
        {% block navigation %}{% include 'navigation.html' %}{% endblock %}
        {% block header %}{% endblock %}
        <main>{% block content %}{% endblock %}</main>
        <footer>{% block footer %}{% include 'footer.html' %}{% endblock %}</footer>
    </body>

    {% block scripts %}{% endblock %}
    {% compress js %}
        <script src="{% static 'js/navigation.js' %}" defer></script>
        <script src="{% static 'js/scroll.js' %}" defer></script>
        <script src="{% static 'js/title.js' %}" defer></script>
    {% endcompress %}
</html>

templates/footer.html
<a href="https://github.com/Fluffy-Bean/Fluffys-website">Website source</a>
<p>Designed by meeee</p>

templates/navigation.html
<nav>
    <a href="{% url 'index' %}">Index</a>
    <a href="{% url 'refsheet' %}">Refsheet</a>
    <a href="{% url 'articles:list' %}">Articles</a>
</nav>

<button class="nav-toggle" onclick="toggleNav();" aria-label="Open Navigation tab">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
        <path d="M224,128a8,8,0,0,1-8,8H136v80a8,8,0,0,1-16,0V136H40a8,8,0,0,1,0-16h80V40a8,8,0,0,1,16,0v80h80A8,8,0,0,1,224,128Z"></path>
    </svg>
</button>

templates/views/article.html
{% extends 'base.html' %}
{% load markdownify %}

{% block title %}{{ article.title }}{% endblock %}

{% block header %}
    <span class="scroll"></span>

    <header>
        <img src="{{ article.thumb.url }}" alt="{{ article.title }}">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date|date:"jS M, Y" }}</p>
    </header>
{% endblock %}

{% block content %}
    <div class="markdown">{{ article.body|markdownify }}</div>
    <a href="{% url 'articles:list' %}" class="back" aria-label="Back to article list">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
            <path d="M232,144a64.07,64.07,0,0,1-64,64H80a8,8,0,0,1,0-16h88a48,48,0,0,0,0-96H51.31l34.35,34.34a8,8,0,0,1-11.32,11.32l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,85.66,45.66L51.31,80H168A64.07,64.07,0,0,1,232,144Z"></path>
        </svg>
    </a>
{% endblock %}

templates/views/articles.html
{% extends 'base.html' %}
{% block content %}
    <h1>Articles</h1>
    {% for article in articles %}
        <a href="{% url 'articles:detail' slug=article.slug %}" class="article">
            <h2>{{ article.title }}</h2>
            <p>{{ article.date|timesince }} ago</p>
        </a>
    {% endfor %}
{% endblock %}

templates/views/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 class="fancy">Leggy&nbsp;Land!!!!!!</h1>
    <h2>About Meeeeee</h2>
    <p>My name is Fluffy, I'm an 18-year-old nerd, who likes to code and tinker with computers!</p>
    <img src="{% static 'images/sneak.png' %}" alt="FluffyBean" style="width:11rem;float:right;" width="178" height="126">
    <p>I specialise in Front-End development, but also enjoy working with the back end.
        My Favorite framework currently is Flask, but this website runs on Django, lol</p>
    <p>My favorite language is Python, but I also know how to use PHP, HTML, CSS/Sass, JavaScript,
        Docker, SQL, Shell Scripting, and a little bit of Rust.</p>
    <p>I also have experience in a few different systems, mainly Arch, Ubuntu and Proxmox.</p>

    <h2>Projects</h2>
    <p>I'm currently working on a few projects, including</p>
    <div class="table">
        <table>
            <tr>
                <th>Name</th>
                <th>Language</th>
                <th>Framework</th>
            </tr>
            <tr>
                <td>This page</td>
                <td>Python</td>
                <td>Django</td>
            </tr>
            <tr>
                <td><a href="https://github.com/Derpy-Leggies/OnlyLegs">OnlyLegs</a></td>
                <td>Python</td>
                <td>Flask</td>
            </tr>
            <tr>
                <td><a href="https://github.com/Fluffy-Bean/Lynxie">Lynxie</a></td>
                <td>Python</td>
                <td>discord.py</td>
            </tr>
            <tr>
                <td>Unnamed Game</td>
                <td>Python & OpenGL</td>
                <td>PyGame & ModernGL</td>
            </tr>
            <tr>
                <td>College</td>
                <td>English</td>
                <td>Suffering</td>
            </tr>
        </table>
    </div>

    <p>And some of my past project include</p>

    <div class="table">
        <table>
            <tr>
                <th>Name</th>
                <th>Language</th>
                <th>Framework</th>
            </tr>
            <tr>
                <td><a href="https://github.com/Fluffy-Bean/image-gallery">OnlyLegs</a></td>
                <td>PHP</td>
                <td>I hate myself</td>
            </tr>
            <tr>
                <td>Joe The Bot V1</td>
                <td>Python</td>
                <td>discord.py</td>
            </tr>
            <tr>
                <td><a href="https://github.com/Fluffy-Bean/Joe_The_Bot">Joe The Bot V2</a></td>
                <td>Typescript</td>
                <td>discord.js</td>
            </tr>
            <tr>
                <td>Twitter Archive Parser</td>
                <td>PHP and Python</td>
                <td>Raw Dogging</td>
            </tr>
            <tr>
                <td>TheFrontRooms</td>
                <td>C# & Python</td>
                <td>Unity & Flask</td>
            </tr>
        </table>
    </div>

    <h2>My Socials</h2>
    <p>Here are my socials, if you want to stalk me</p>

    <div class="button-array">
        <a style="width: auto; padding:0.5rem 0.7rem" href="https://twitter.com/fluffybeanUwU">Twitter</a>
        <a style="width: auto; padding:0.5rem 0.7rem" href="https://bsky.app/profile/leggy.dev">BlueSky</a>
        <a style="width: auto; padding:0.5rem 0.7rem" rel="me" href="https://meow.social/@Fluffy_Bean">Mastodon</a>
        <a style="width: auto; padding:0.5rem 0.7rem" href="https://t.me/Fluffy_Bean">Telegram</a>
        <a style="width: auto; padding:0.5rem 0.7rem" href="https://github.com/Fluffy-Bean">Github</a>
        <a style="width: auto; padding:0.5rem 0.7rem" href="https://www.last.fm/user/Fluffy_Bean_">LastFM</a>
    </div>

    <p style="margin-bottom: 0">Please don't message me with a "hi" or "hello, how are you". Start a meaningful conversation,
    chances of me responding will be slim otherwise!</p>
{% endblock %}

templates/views/refsheet.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Fluffeeeeee</h1>
    <h2>Refsheet</h2>
    <img src="{% static 'images/ref.png' %}" alt="FluffyBean">
    <div class="button-array">
        <p>mrHDash</p>
        <a href="https://twitter.com/mrHDash">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
            </svg>
        </a>
        <a href="https://instagram.com/mrhdash_arts">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                <path d="M128,80a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160ZM176,24H80A56.06,56.06,0,0,0,24,80v96a56.06,56.06,0,0,0,56,56h96a56.06,56.06,0,0,0,56-56V80A56.06,56.06,0,0,0,176,24Zm40,152a40,40,0,0,1-40,40H80a40,40,0,0,1-40-40V80A40,40,0,0,1,80,40h96a40,40,0,0,1,40,40ZM192,76a12,12,0,1,1-12-12A12,12,0,0,1,192,76Z"></path>
            </svg>
        </a>
    </div>

    <h2>Art</h2>
    <div class="art-block">
        <div class="art" id="sneak">
            <span><img src="{% static 'images/sneak.png' %}" alt="FluffyBean"></span>
            <div class="button-array">
                <p>Shep</p>
                <a href="https://twitter.com/ShepGoesBlep">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
                    </svg>
                </a>
            </div>
        </div>

        <div class="art" id="taidum">
            <span><img src="{% static 'images/taidum.png' %}" alt="FluffyBean"></span>
            <div class="button-array">
                <p>Zadok</p>
                <a href="https://twitter.com/Zadoktater">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
                    </svg>
                </a>
                <button onclick="navigator.clipboard.writeText('zadoknchip'); return;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M104,140a12,12,0,1,1-12-12A12,12,0,0,1,104,140Zm60-12a12,12,0,1,0,12,12A12,12,0,0,0,164,128Zm74.45,64.9-67,29.71a16.17,16.17,0,0,1-21.71-9.1l-8.11-22q-6.72.45-13.63.46t-13.63-.46l-8.11,22a16.18,16.18,0,0,1-21.71,9.1l-67-29.71a15.93,15.93,0,0,1-9.06-18.51L38,58A16.07,16.07,0,0,1,51,46.14l36.06-5.93a16.22,16.22,0,0,1,18.26,11.88l3.26,12.84Q118.11,64,128,64t19.4.93l3.26-12.84a16.21,16.21,0,0,1,18.26-11.88L205,46.14A16.07,16.07,0,0,1,218,58l29.53,116.38A15.93,15.93,0,0,1,238.45,192.9ZM232,178.28,202.47,62s0,0-.08,0L166.33,56a.17.17,0,0,0-.17,0l-2.83,11.14c5,.94,10,2.06,14.83,3.42A8,8,0,0,1,176,86.31a8.09,8.09,0,0,1-2.16-.3A172.25,172.25,0,0,0,128,80a172.25,172.25,0,0,0-45.84,6,8,8,0,1,1-4.32-15.4c4.82-1.36,9.78-2.48,14.82-3.42L89.83,56s0,0-.12,0h0L53.61,61.93a.17.17,0,0,0-.09,0L24,178.33,91,208a.23.23,0,0,0,.22,0L98,189.72a173.2,173.2,0,0,1-20.14-4.32A8,8,0,0,1,82.16,170,171.85,171.85,0,0,0,128,176a171.85,171.85,0,0,0,45.84-6,8,8,0,0,1,4.32,15.41A173.2,173.2,0,0,1,158,189.72L164.75,208a.22.22,0,0,0,.21,0Z"></path>
                    </svg>
                </button>
            </div>
        </div>

        <div class="art" id="cross-eyes">
            <span><img src="{% static 'images/cross-eyes.png' %}" alt="FluffyBean"></span>
            <div class="button-array">
                <p>Zadok</p>
                <a href="https://twitter.com/Zadoktater">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
                    </svg>
                </a>
                <button onclick="navigator.clipboard.writeText('zadoknchip'); return;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M104,140a12,12,0,1,1-12-12A12,12,0,0,1,104,140Zm60-12a12,12,0,1,0,12,12A12,12,0,0,0,164,128Zm74.45,64.9-67,29.71a16.17,16.17,0,0,1-21.71-9.1l-8.11-22q-6.72.45-13.63.46t-13.63-.46l-8.11,22a16.18,16.18,0,0,1-21.71,9.1l-67-29.71a15.93,15.93,0,0,1-9.06-18.51L38,58A16.07,16.07,0,0,1,51,46.14l36.06-5.93a16.22,16.22,0,0,1,18.26,11.88l3.26,12.84Q118.11,64,128,64t19.4.93l3.26-12.84a16.21,16.21,0,0,1,18.26-11.88L205,46.14A16.07,16.07,0,0,1,218,58l29.53,116.38A15.93,15.93,0,0,1,238.45,192.9ZM232,178.28,202.47,62s0,0-.08,0L166.33,56a.17.17,0,0,0-.17,0l-2.83,11.14c5,.94,10,2.06,14.83,3.42A8,8,0,0,1,176,86.31a8.09,8.09,0,0,1-2.16-.3A172.25,172.25,0,0,0,128,80a172.25,172.25,0,0,0-45.84,6,8,8,0,1,1-4.32-15.4c4.82-1.36,9.78-2.48,14.82-3.42L89.83,56s0,0-.12,0h0L53.61,61.93a.17.17,0,0,0-.09,0L24,178.33,91,208a.23.23,0,0,0,.22,0L98,189.72a173.2,173.2,0,0,1-20.14-4.32A8,8,0,0,1,82.16,170,171.85,171.85,0,0,0,128,176a171.85,171.85,0,0,0,45.84-6,8,8,0,0,1,4.32,15.41A173.2,173.2,0,0,1,158,189.72L164.75,208a.22.22,0,0,0,.21,0Z"></path>
                    </svg>
                </button>
            </div>
        </div>

        <div class="art" id="kissing-men">
            <span><img src="{% static 'images/kissing-men.png' %}" alt="FluffyBean"></span>
            <div class="button-array">
                <p>LordPulex</p>
                <a href="https://twitter.com/LordPulex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
                    </svg>
                </a>
                <a href="https://pulex.carrd.co/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM101.63,168h52.74C149,186.34,140,202.87,128,215.89,116,202.87,107,186.34,101.63,168ZM98,152a145.72,145.72,0,0,1,0-48h60a145.72,145.72,0,0,1,0,48ZM40,128a87.61,87.61,0,0,1,3.33-24H81.79a161.79,161.79,0,0,0,0,48H43.33A87.61,87.61,0,0,1,40,128ZM154.37,88H101.63C107,69.66,116,53.13,128,40.11,140,53.13,149,69.66,154.37,88Zm19.84,16h38.46a88.15,88.15,0,0,1,0,48H174.21a161.79,161.79,0,0,0,0-48Zm32.16-16H170.94a142.39,142.39,0,0,0-20.26-45A88.37,88.37,0,0,1,206.37,88ZM105.32,43A142.39,142.39,0,0,0,85.06,88H49.63A88.37,88.37,0,0,1,105.32,43ZM49.63,168H85.06a142.39,142.39,0,0,0,20.26,45A88.37,88.37,0,0,1,49.63,168Zm101.05,45a142.39,142.39,0,0,0,20.26-45h35.43A88.37,88.37,0,0,1,150.68,213Z"></path>
                    </svg>
                </a>
            </div>
        </div>

        <div class="art" id="mood">
            <span><img src="{% static 'images/mood.png' %}" alt="FluffyBean"></span>
            <div class="button-array">
                <p>OggyTheFox</p>
                <a href="https://twitter.com/OggyOsbourne">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M247.39,68.94A8,8,0,0,0,240,64H209.57A48.66,48.66,0,0,0,168.1,40a46.91,46.91,0,0,0-33.75,13.7A47.9,47.9,0,0,0,120,88v6.09C79.74,83.47,46.81,50.72,46.46,50.37a8,8,0,0,0-13.65,4.92c-4.31,47.79,9.57,79.77,22,98.18a110.93,110.93,0,0,0,21.88,24.2c-15.23,17.53-39.21,26.74-39.47,26.84a8,8,0,0,0-3.85,11.93c.75,1.12,3.75,5.05,11.08,8.72C53.51,229.7,65.48,232,80,232c70.67,0,129.72-54.42,135.75-124.44l29.91-29.9A8,8,0,0,0,247.39,68.94Zm-45,29.41a8,8,0,0,0-2.32,5.14C196,166.58,143.28,216,80,216c-10.56,0-18-1.4-23.22-3.08,11.51-6.25,27.56-17,37.88-32.48A8,8,0,0,0,92,169.08c-.47-.27-43.91-26.34-44-96,16,13,45.25,33.17,78.67,38.79A8,8,0,0,0,136,104V88a32,32,0,0,1,9.6-22.92A30.94,30.94,0,0,1,167.9,56c12.66.16,24.49,7.88,29.44,19.21A8,8,0,0,0,204.67,80h16Z"></path>
                    </svg>
                </a>
                <a href="https://oggy123.eu/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 256 256">
                        <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM101.63,168h52.74C149,186.34,140,202.87,128,215.89,116,202.87,107,186.34,101.63,168ZM98,152a145.72,145.72,0,0,1,0-48h60a145.72,145.72,0,0,1,0,48ZM40,128a87.61,87.61,0,0,1,3.33-24H81.79a161.79,161.79,0,0,0,0,48H43.33A87.61,87.61,0,0,1,40,128ZM154.37,88H101.63C107,69.66,116,53.13,128,40.11,140,53.13,149,69.66,154.37,88Zm19.84,16h38.46a88.15,88.15,0,0,1,0,48H174.21a161.79,161.79,0,0,0,0-48Zm32.16-16H170.94a142.39,142.39,0,0,0-20.26-45A88.37,88.37,0,0,1,206.37,88ZM105.32,43A142.39,142.39,0,0,0,85.06,88H49.63A88.37,88.37,0,0,1,105.32,43ZM49.63,168H85.06a142.39,142.39,0,0,0,20.26,45A88.37,88.37,0,0,1,49.63,168Zm101.05,45a142.39,142.39,0,0,0,20.26-45h35.43A88.37,88.37,0,0,1,150.68,213Z"></path>
                    </svg>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        const art = document.querySelectorAll('.art');

        art.forEach((art) => {
            art.style.height = art.clientWidth + 'px';
        });

        window.onresize = () => {
            art.forEach((art) => {
                art.style.height = art.clientWidth + 'px';
            });
        }
    </script>
{% endblock %}